"""
Scraper konfigürasyonu — football-data.co.uk CSV kaynağı için lig kodları.
"""
import os

# football-data.co.uk lig kodları → lig adı
# Sezon CSV URL formatı: https://www.football-data.co.uk/mmz4281/{sezon}/{kod}.csv
LEAGUES: dict[str, str] = {
    "T1":  "Türkiye Süper Lig",
    "T2":  "Türkiye 1. Lig",
    "E0":  "İngiltere Premier Lig",
    "E1":  "İngiltere Championship",
    "E2":  "İngiltere League 1",
    "E3":  "İngiltere League 2",
    "EC":  "İngiltere National League",
    "SP1": "İspanya La Liga",
    "SP2": "İspanya Segunda Division",
    "D1":  "Almanya Bundesliga",
    "D2":  "Almanya 2. Bundesliga",
    "I1":  "İtalya Serie A",
    "I2":  "İtalya Serie B",
    "F1":  "Fransa Ligue 1",
    "F2":  "Fransa Ligue 2",
    "N1":  "Hollanda Eredivisie",
    "P1":  "Portekiz Primeira Liga",
    "B1":  "Belçika Pro League",
    "SC0": "İskoçya Premiership",
    "SC1": "İskoçya Championship",
    "G1":  "Yunanistan Super League",
    "R1":  "Romanya Liga 1",
}

# Kaç sezon geriye gidilsin (mevcut sezon dahil)
SEASONS_BACK: int = 4  # ör. 2024/25, 2023/24, 2022/23, 2021/22

# Kaç aylık geçmiş veri çekilsin (worker başlangıç filtresi için)
MONTHS_BACK: int = 12

# İstekler arası bekleme (saniye) — CSV'ler tek istek, fazla agresif olma
DELAY_MIN: float = 1.5
DELAY_MAX: float = 3.5

# Alt-istek bekleme (artık kullanılmıyor ama uyumluluk için)
SUB_DELAY_MIN: float = 0.5
SUB_DELAY_MAX: float = 1.0

# Flask kontrol sunucusu portu (dahili, dışarıya açık değil)
FLASK_PORT: int = 5051

# SQLite veritabanı yolu (proje köküne göre)
_BASE = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH: str = os.path.join(_BASE, "database", "gecmis_maclar.db")

# İstek başına yeniden deneme sayısı
MAX_RETRIES: int = 3

# football-data.co.uk base URL
FDUK_BASE: str = "https://www.football-data.co.uk/mmz4281"

# SofaScore Unique Tournament IDs
SOFASCORE_TOURNAMENTS: dict[str, int] = {
    "Şampiyonlar Ligi": 7,
    "UEFA Avrupa Ligi": 679,
    "Konferans Ligi": 17015,
    "Dünya Kupası": 1,
    "Avrupa Şampiyonası": 2,
    "Türkiye Süper Lig": 52,
    "Türkiye 1. Lig": 99,
    "İngiltere Premier Lig": 17,
    "İngiltere Championship": 18,
    "İngiltere League 1": 24,
    "İngiltere League 2": 25,
    "İngiltere National League": 46,
    "İspanya La Liga": 8,
    "İspanya Segunda Division": 54,
    "Almanya Bundesliga": 35,
    "Almanya 2. Bundesliga": 44,
    "İtalya Serie A": 23,
    "İtalya Serie B": 53,
    "Fransa Ligue 1": 34,
    "Fransa Ligue 2": 182,
    "Hollanda Eredivisie": 37,
    "Portekiz Primeira Liga": 238,
    "Belçika Pro League": 38,
    "İskoçya Premiership": 36,
    "İskoçya Championship": 47,
    "Yunanistan Super League": 185,
    "Romanya Liga 1": 152,
    "Romanya Liga 2": 562,
    "Sırbistan SuperLiga": 210,
    "Sırbistan Prva Liga": 721,
    "Bulgaristan Parva Liga": 247,
    "Bulgaristan Vtora Liga": 1135,
    "Litvanya A Lyga": 198,
    "Estonya Premium Liiga": 178,
    "Letonya Virsliga": 197,
    "Çekya 1. Ligi": 172,
    "Macaristan NB I": 816,
    "Slovakya Niké Liga": 211,
    "Slovenya PrvaLiga": 212,
    "Ukrayna Premier Ligi": 218,
    "Azerbaycan Premier Ligi": 709,
    "Kazakistan Premier Ligi": 682,
    "İsrail Premier Ligi": 266,
    "Kıbrıs Rum Kesimi 1. Ligi": 171,
    "Mısır Premier Ligi": 808,
    "Fas Botola Pro": 937,
    "İran Persian Gulf Pro League": 915,
    "İrlanda Premier Division": 192,
    "Kuzey İrlanda NIFL Premiership": 200,
    "Galler Cymru Premier": 254,
    "Güney Afrika Premier Division": 358,
    "Olimpiyat Oyunları": 436,
    "UEFA Nations League": 10783,
    "Dünya Kupası Elemeleri (UEFA)": 11,
    "Dünya Kupası Elemeleri (CONMEBOL)": 295,
    "Dünya Kupası Elemeleri (CAF)": 13,
    "Dünya Kupası Elemeleri (AFC)": 308,
    "Dünya Kupası Elemeleri (CONCACAF)": 14,
    "Singapur Premier League": 634,
    "Malezya Süper Ligi": 1000,
    "Katar Yıldızlar Ligi": 825,
    "BAE Pro Ligi": 971,
    "Tayland 1. Ligi": 1032,
    "Norveç Eliteserien": 20,
    "Norveç 1. Lig": 22,
    "ABD MLS": 242,
    "Kanada Premier Ligi": 1523,
    "İsveç Allsvenskan": 40,
    "İsveç Superettan": 46,
    "İzlanda Besta deild karla": 188,
    "İzlanda 1. deild": 675,
    "Danimarka Superligaen": 39,
    "Danimarka 1. Division": 1416,
    "Finlandiya Veikkausliiga": 41,
    "Finlandiya Ykkösliiga": 55,
    "Brezilya Serie A": 325,
    "Brezilya Serie B": 390,
    "Meksika Liga MX Apertura": 11621,
    "Meksika Liga MX Clausura": 11620,
    "Meksika Liga de Expansion Apertura": 11611,
    "Meksika Liga de Expansion Clausura": 11612,
    "Arjantin Primera Division": 155,
    "Arjantin Primera Nacional": 703,
    "Ekvador LigaPro Serie A": 240,
    "Paraguay Primera Division Apertura": 11540,
    "Paraguay Primera Division Clausura": 11541,
    "Bolivya Division Profesional": 16736,
    "Polonya Ekstraklasa": 202,
    "Polonya I Liga": 11453,
    "Avusturya Bundesliga": 45,
    "Avusturya 2. Liga": 135,
    "Avustralya A-League": 136,
    "Avustralya NPL Victoria": 1275,
    "Avustralya NPL New South Wales": 1274,
    "Japonya J1 League": 196,
    "Japonya J2 League": 402,
    "Güney Kore K League 1": 410,
    "Güney Kore K League 2": 777,
    "Almanya 3. Liga": 491,
    "İsviçre Super League": 215,
    "İsviçre Challenge League": 216,
    "Hollanda Eerste Divisie": 131,
    "Kolombiya Primera A Apertura": 11539,
    "Kolombiya Primera A Finalizacion": 11536,
    "Şili Liga de Primera": 11653,
    "Suudi Arabistan Pro League": 955,
    "Çin Süper Ligi": 649,
    "Copa Libertadores": 16940,
    "Copa Sudamericana": 480,
    "Rusya Premier Ligi": 203,
    "Hırvatistan HNL": 170,
    "İngiltere FA Cup": 19,
    "İngiltere EFL Cup": 21,
    "İngiltere Community Shield": 346,
    "İspanya Copa del Rey": 329,
    "İspanya Supercopa": 213,
    "Almanya DFB Pokal": 217,
    "Almanya Supercup": 799,
    "İtalya Coppa Italia": 328,
    "İtalya Supercoppa": 341,
    "Fransa Coupe de France": 335,
    "Fransa Trophée des Champions": 339,
    "Türkiye Kupası": 96,
    "TFF Süper Kupa": 505,
    "Portekiz Taça de Portugal": 336,
    "Portekiz Taça da Liga": 327,
    "Hollanda KNVB Beker": 330,
    "Hollanda Johan Cruijff Schaal": 340,
    "Belçika Kupası": 326,
    "İskoçya FA Cup": 347,
    "İskoçya League Cup": 332,
    "Yunanistan Kupası": 375,
    "Romanya Kupası": 355,
    "Romanya Supercupa": 698,
    "Brezilya Copa do Brasil": 373,
    "Arjantin Copa Argentina": 1024,
    "Arjantin Copa de la Liga Profesional": 13475,
    "Meksika Copa MX": 1598,
    "Kolombiya Copa Colombia": 1335,
    "Şili Copa Chile": 1221,
    "Rusya Kupası": 91,
    "Rusya Supercup": 397,
    "Suudi Arabistan King's Cup": 2058,
    "Japonya Emperor's Cup": 323,
    "Güney Kore Kore Kupası": 615,
    "İsviçre Kupası": 399,
    "Polonya Kupası": 281,
    "UEFA Süper Kupası": 465,
    "FIFA Kulüpler Dünya Kupası": 357,
}
