import { Router, type IRouter } from "express";
import { AnalyzeMatchesBody } from "@workspace/api-zod";
import { analyze } from "../lib/analyzeEngine";

const router: IRouter = Router();

router.post("/analyze", (req, res): void => {
  const parsed = AnalyzeMatchesBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  const { targetMatch, referenceMatches } = parsed.data;
  console.log("TEST LEAGUE AFTER PARSE:", referenceMatches[0]?.league);

  const result = analyze(
    {
      date:          targetMatch.date          ?? null,
      time:          targetMatch.time          ?? null,
      league:        targetMatch.league        ?? null,
      homeTeam:      targetMatch.homeTeam,
      awayTeam:      targetMatch.awayTeam,
      ligSirasiHome: targetMatch.ligSirasiHome ?? null,
      ligSirasiAway: targetMatch.ligSirasiAway ?? null,
      ligSirasiTotal:targetMatch.ligSirasiTotal ?? null,
      oddsHome:      targetMatch.oddsHome      ?? null,
      oddsDraw:      targetMatch.oddsDraw      ?? null,
      oddsAway:      targetMatch.oddsAway      ?? null,
      altOdds:       targetMatch.altOdds       ?? null,
      ustOdds:       targetMatch.ustOdds       ?? null,
      varOdds:       targetMatch.varOdds       ?? null,
      yokOdds:       targetMatch.yokOdds       ?? null,
      altOdds35:     targetMatch.altOdds35     ?? null,
      ustOdds35:     targetMatch.ustOdds35     ?? null,
      iyAltOdds15:   targetMatch.iyAltOdds15   ?? null,
      iyUstOdds15:   targetMatch.iyUstOdds15   ?? null,
      iyAltOdds05:   targetMatch.iyAltOdds05   ?? null,
      iyUstOdds05:   targetMatch.iyUstOdds05   ?? null,
      avgOddsMin:    targetMatch.avgOddsMin    ?? null,
      avgOddsMax:    targetMatch.avgOddsMax    ?? null,
      oran_1_acilis:    (req.body.targetMatch as any)?.oran_1_acilis    ?? null,
      oran_x_acilis:    (req.body.targetMatch as any)?.oran_x_acilis    ?? null,
      oran_2_acilis:    (req.body.targetMatch as any)?.oran_2_acilis    ?? null,
      alt_orani_acilis: (req.body.targetMatch as any)?.alt_orani_acilis ?? null,
      ust_orani_acilis: (req.body.targetMatch as any)?.ust_orani_acilis ?? null,
      kg_var_acilis:    (req.body.targetMatch as any)?.kg_var_acilis    ?? null,
      kg_yok_acilis:    (req.body.targetMatch as any)?.kg_yok_acilis    ?? null,
      alt_orani_35_acilis: (req.body.targetMatch as any)?.alt_orani_35_acilis ?? null,
      ust_orani_35_acilis: (req.body.targetMatch as any)?.ust_orani_35_acilis ?? null,
      iy_alt_orani_15_acilis: (req.body.targetMatch as any)?.iy_alt_orani_15_acilis ?? null,
      iy_ust_orani_15_acilis: (req.body.targetMatch as any)?.iy_ust_orani_15_acilis ?? null,
      iy_alt_orani_05_acilis: (req.body.targetMatch as any)?.iy_alt_orani_05_acilis ?? null,
      iy_ust_orani_05_acilis: (req.body.targetMatch as any)?.iy_ust_orani_05_acilis ?? null,
      oran_1_kapanis:    (req.body.targetMatch as any)?.oran_1_kapanis    ?? null,
      oran_x_kapanis:    (req.body.targetMatch as any)?.oran_x_kapanis    ?? null,
      oran_2_kapanis:    (req.body.targetMatch as any)?.oran_2_kapanis    ?? null,
      alt_orani_kapanis: (req.body.targetMatch as any)?.alt_orani_kapanis ?? null,
      ust_orani_kapanis: (req.body.targetMatch as any)?.ust_orani_kapanis ?? null,
      kg_var_kapanis:    (req.body.targetMatch as any)?.kg_var_kapanis    ?? null,
      kg_yok_kapanis:    (req.body.targetMatch as any)?.kg_yok_kapanis    ?? null,
      alt_orani_35_kapanis: (req.body.targetMatch as any)?.alt_orani_35_kapanis ?? null,
      ust_orani_35_kapanis: (req.body.targetMatch as any)?.ust_orani_35_kapanis ?? null,
      iy_alt_orani_15_kapanis: (req.body.targetMatch as any)?.iy_alt_orani_15_kapanis ?? null,
      iy_ust_orani_15_kapanis: (req.body.targetMatch as any)?.iy_ust_orani_15_kapanis ?? null,
      iy_alt_orani_05_kapanis: (req.body.targetMatch as any)?.iy_alt_orani_05_kapanis ?? null,
      iy_ust_orani_05_kapanis: (req.body.targetMatch as any)?.iy_ust_orani_05_kapanis ?? null,
    },
    referenceMatches.map((m, idx) => ({
      id:              m.id              ?? null,
      league: m.league ?? null,
      matchDate: m.matchDate ?? null,
      similarityScore: (req.body.referenceMatches?.[idx] as any)?.similarityScore ?? null,
      homeTeam:        m.homeTeam,
      awayTeam:        m.awayTeam,
      htScore:         m.htScore         ?? null,
      ftScore:         m.ftScore,
      previousScore:   m.previousScore   ?? null,
      yellowCardsHome: m.yellowCardsHome ?? null,
      yellowCardsAway: m.yellowCardsAway ?? null,
      redCards:        m.redCards        ?? null,
      ligSirasiHome:   m.ligSirasiHome   ?? null,
      ligSirasiAway:   m.ligSirasiAway   ?? null,
      ligSirasiTotal:  m.ligSirasiTotal  ?? null,
      oddsHome:        m.oddsHome        ?? null,
      oddsDraw:        m.oddsDraw        ?? null,
      oddsAway:        m.oddsAway        ?? null,
      altOdds:         m.altOdds         ?? null,
      ustOdds:         m.ustOdds         ?? null,
      varOdds:         m.varOdds         ?? null,
      yokOdds:         m.yokOdds         ?? null,
      altOdds35:       m.altOdds35       ?? null,
      ustOdds35:       m.ustOdds35       ?? null,
      iyAltOdds15:     m.iyAltOdds15     ?? null,
      iyUstOdds15:     m.iyUstOdds15     ?? null,
      iyAltOdds05:     m.iyAltOdds05     ?? null,
      iyUstOdds05:     m.iyUstOdds05     ?? null,
      avgOddsMin:      m.avgOddsMin      ?? null,
      avgOddsMax:      m.avgOddsMax      ?? null,
      imResult:        m.imResult        ?? null,
      kornerHome:      m.kornerHome      ?? null,
      kornerAway:      m.kornerAway      ?? null,
      oran_1_acilis:    (req.body.referenceMatches?.[idx] as any)?.oran_1_acilis    ?? null,
      oran_x_acilis:    (req.body.referenceMatches?.[idx] as any)?.oran_x_acilis    ?? null,
      oran_2_acilis:    (req.body.referenceMatches?.[idx] as any)?.oran_2_acilis    ?? null,
      alt_orani_acilis: (req.body.referenceMatches?.[idx] as any)?.alt_orani_acilis ?? null,
      ust_orani_acilis: (req.body.referenceMatches?.[idx] as any)?.ust_orani_acilis ?? null,
      kg_var_acilis:    (req.body.referenceMatches?.[idx] as any)?.kg_var_acilis    ?? null,
      kg_yok_acilis:    (req.body.referenceMatches?.[idx] as any)?.kg_yok_acilis    ?? null,
      alt_orani_35_acilis: (req.body.referenceMatches?.[idx] as any)?.alt_orani_35_acilis ?? null,
      ust_orani_35_acilis: (req.body.referenceMatches?.[idx] as any)?.ust_orani_35_acilis ?? null,
      iy_alt_orani_15_acilis: (req.body.referenceMatches?.[idx] as any)?.iy_alt_orani_15_acilis ?? null,
      iy_ust_orani_15_acilis: (req.body.referenceMatches?.[idx] as any)?.iy_ust_orani_15_acilis ?? null,
      iy_alt_orani_05_acilis: (req.body.referenceMatches?.[idx] as any)?.iy_alt_orani_05_acilis ?? null,
      iy_ust_orani_05_acilis: (req.body.referenceMatches?.[idx] as any)?.iy_ust_orani_05_acilis ?? null,
      oran_1_kapanis:    (req.body.referenceMatches?.[idx] as any)?.oran_1_kapanis    ?? null,
      oran_x_kapanis:    (req.body.referenceMatches?.[idx] as any)?.oran_x_kapanis    ?? null,
      oran_2_kapanis:    (req.body.referenceMatches?.[idx] as any)?.oran_2_kapanis    ?? null,
      alt_orani_kapanis: (req.body.referenceMatches?.[idx] as any)?.alt_orani_kapanis ?? null,
      ust_orani_kapanis: (req.body.referenceMatches?.[idx] as any)?.ust_orani_kapanis ?? null,
      kg_var_kapanis:    (req.body.referenceMatches?.[idx] as any)?.kg_var_kapanis    ?? null,
      kg_yok_kapanis:    (req.body.referenceMatches?.[idx] as any)?.kg_yok_kapanis    ?? null,
      alt_orani_35_kapanis: (req.body.referenceMatches?.[idx] as any)?.alt_orani_35_kapanis ?? null,
      ust_orani_35_kapanis: (req.body.referenceMatches?.[idx] as any)?.ust_orani_35_kapanis ?? null,
      iy_alt_orani_15_kapanis: (req.body.referenceMatches?.[idx] as any)?.iy_alt_orani_15_kapanis ?? null,
      iy_ust_orani_15_kapanis: (req.body.referenceMatches?.[idx] as any)?.iy_ust_orani_15_kapanis ?? null,
      iy_alt_orani_05_kapanis: (req.body.referenceMatches?.[idx] as any)?.iy_alt_orani_05_kapanis ?? null,
      iy_ust_orani_05_kapanis: (req.body.referenceMatches?.[idx] as any)?.iy_ust_orani_05_kapanis ?? null,
      matchDate:        (req.body.referenceMatches?.[idx] as any)?.matchDate ?? (m as any).matchDate ?? null,
    })),
    req.body.config
  );

  res.json(result);
});

export default router;
